### PR TITLE
reinstate The Rabbit Hole

### PR DESCRIPTION
**Pull request by quietly-turning**
This reverts commit 068632f077ad143d151d8ebc92618028e3e3bddf.

It is immensely important that The Rabbit Hole remains intact.  It is the heart of the project.

### CODE REVIEW

**Comment by Tiktalik** [comment]
https://github.com/48productions/Simply-Potato-SM5/commit/068632f077ad143d151d8ebc92618028e3e3bddf#commitcomment-37320106

Who got to you

(But no, seriously, some context on what The Rabbit Hole is and what relevance it has to the theme would be nice.)

**Comment by 48productions** [comment]
You make a convincing argument, the theme just feels massively incomplete without it. I don't even know how many hours I've lost diving down it in the original Simply Love...

**Comment by quietly-turning** [comment]
> some context on what The Rabbit Hole is and what relevance it has to the theme would be nice.

The Rabbit Hole first appeared in [the 4.8 release](https://github.com/quietly-turning/Simply-Love-SM5/releases/tag/4.8), dubbed the "Extra Stage" release for reasons left opaque at that time that I'll attempt to clarify now.

It is a collection of essays, poems, composition, thoughts, and feelings created between May and July of 2018.  It is the direct answer to my own efforts to [stop work on Simply Love after the 4.7 release](https://github.com/quietly-turning/Simply-Love-SM5/releases/tag/4.7).

At that time I was newly out of the hospital where I'd been for a while following an unsuccessful suicide attempt.  Absolutely nothing made sense, but I understood I needed something to work on or I would be back there quickly.

I collected my thoughts on what it felt like to try to live and to love, the two things I struggled the most with. I wrote down those thoughts and I typed code and arranged music every single day for nearly three months. Distinct ideas and themes started to emerge, and eventually chapters did too. 

The Rabbit Hole is the heart of Simply Love.   The multitude of heart-shaped png assets are a presentable face for the public and without The Rabbit Hole they become hollow and bloodless.

Thanks for understanding.

**Comment by quietly-turning** [comment]
Hey, I'm sorry about the way I behaved here, and overall with the team that worked on Simply-Potato-SM5.

While it's true that I'd Been Through Some Stuff in 2018, that absolutely didn't justify me forcefully dictating the way anyone used Simply-Love-SM5.  My request here went against the spirit of me open-sourcing the thing in the first place. 

A more helpful pull request would have been to myself, telling myself to take a step back.  I've been reflecting on this for a while, and wanted to acknowledge:

* The way I behaved here wasn't cool.
* You all handled me with grace.
* I really like that you've continued to work on this project!  I think your attention to Casual Mode is awesome! :)

**Comment by 48productions** [comment]
Sorry for the late reply, no worries! I don't think any of us realized just how much history was behind the Rabbit Hole, and it was interesting to hear the story behind how it came to be. You certainly put a LOT of time and effort into it, and I can fully understand being upset to see all of that work get removed.

Along those lines, I'm 100% okay with keeping the Rabbit Hole in the theme, to preserve the meaning and purpose behind it. But if there's any reason you'd prefer it to no longer be in the theme (I see it's since been removed from mainline SL, if I'm not mistaken), then that's perfectly okay too.

Glad to hear you're liking Casual Mode, as well! It's been a long-running goal to try and really polish the experience for new and intermediate players, and it's certainly been paying off. The cabinet that this theme was developed for is getting plenty of attention in the arcade, and I've ran into a number of local players who are either just getting into or rediscovering their love for dance games.

**Comment by quietly-turning** [comment]
> The cabinet that this theme was developed for is getting plenty of attention in the arcade, and I've ran into a number of local players who are either just getting into or rediscovering their love for dance games.

This makes me smile to hear. :)

As for keeping this in the theme or removing it — this fork is yours and what you do with it is up to you.

**Pull request merged**
